### ISSUE TITLE
Using environment variables from .env file under vscode

### ISSUE THREAD

**Issue by g41797** [staticbackendhq/core#93]
**Is your feature request related to a problem? Please describe.**
go code reads os(shell) environment variables via os.Getenv("name") API.
In order to get values for development saved in .env file, path to this file should be added to json config files of IDE. Cumbersome process.

**Describe the solution you'd like**

Use new config.Getenv("name")
1. [Once] Read .env file and inject values to environment (using [godotenv](https://github.com/joho/godotenv) )
2. call os.Getenv

**Describe alternatives you've considered**
Add env variables to .vscode/launch.json and save it in repository
something like:

```json
            "env": {
                "DEV_ENV": "true",
                "DOCKER_ENV": "true",
            }
```

**Additional context** [Example of godotenv usage](https://towardsdatascience.com/use-environment-variable-in-your-next-golang-project-39e17c3aaa66)

**Comment by dstpierre** [comment]
Maybe instead of bringing another dependency the `config.LoadConfig()` function could check for presence of `.env` and load the `AppConfig` based on those values instead of getting them from the system environment variables.

Something like:

**config/config.go** line:85

```go
func LoadConfig() AppConfig {
  if .env exists {
    return loadFromEnvFile()
  }

  // load from system environement variables
}
```
Format of `.env` is fairly straightforward to parse, maybe into a map[string]string spliting by `\n` and by `=` would give key, value, from there the `AppConfig` could be filled with all values.

What do you think?

**Comment by g41797** [comment]
see [Example of vscode conf](https://github.com/memphisdev/memphis/blob/master/.vscode/launch.json)

Now I think to add .vscode/launch.json with some default configurations will be simplest solution
